### ISSUE TITLE
Transaction references bug, don't know how to deal with this 

### ISSUE THREAD

**Issue by mpdehaan** [chiselstrike/chiselstrike#1184]
The user won't know what to do with this error.  I just restarted chiseld and tried to do a POST and got this:

```
WARN - Commit failed: Transaction still have references held!
```

There's no traceback or list of what SQL statement was involved, or suggestion of what to do about this.

**Comment by glommer** [comment]
Seems like the other bug is closed, and unfortunately the forgot await thing is a limitation of typescript tools. Linters help but they forget a bunch too.
