### ISSUE TITLE
We need a way to wait for secrets to be updated

### ISSUE THREAD

**Issue by espindola** [chiselstrike/chiselstrike#1355]
The test cli/tests/lit/secrets.deno is full of sleeps because there is no way to wait for secrets to be updated. We should probably have a "chisel reload-secrets" that triggers a manual reload and waits for it to happen.

**Comment by espindola** [comment]
It might be better for the command to not actually trigger a reload, just wait for the in disk content to match. That way we still test that we do hot reload.

**Comment by dekimir** [comment]
> We should probably have a "chisel reload-secrets" that triggers a manual reload and waits for it to happen.

FWIW, this is a part of what `chisel restart` does.  Thus
https://github.com/chiselstrike/chiselstrike/blob/5a3e8301eabef533eccfbff38e05173add6500a7/cli/tests/lit/auth-header.node#L12-L13

**Comment by espindola** [comment]
> > We should probably have a "chisel reload-secrets" that triggers a manual reload and waits for it to happen.
> 
> FWIW, this is a part of what `chisel restart` does. Thus
> 
> https://github.com/chiselstrike/chiselstrike/blob/5a3e8301eabef533eccfbff38e05173add6500a7/cli/tests/lit/auth-header.node#L12-L13

Thanks! PR in

https://github.com/chiselstrike/chiselstrike/pull/1365

**Comment by espindola** [comment]
I will close this again since in https://github.com/chiselstrike/chiselstrike/issues/1375 we decided to have a "chisel load-secret" command.
