### ISSUE TITLE
Passing argument from cli to server on launch

### ISSUE THREAD

**Issue by MarinPostma** [chiselstrike/chiselstrike#1481]
Right now, I want to develop with some custom server parameters (I'm mostly thinking of changing the address and port to which it serves), and I need to spin an independent chiseld instance. This is not very user-friendly. It would be handy to pass arguments to the cli, that are passed to the server. On the top of my head, I'm thinking that any arguments passed after `--` could be passed when launching the server.

Also considering that passing any argument to the server could put it in a state that makes it impossible to operate with the cli out of the box...

could be related to https://github.com/chiselstrike/chiselstrike/issues/1479

**Comment by penberg** [comment]
@MarinPostma This is fixed now, isn't it?

**Comment by MarinPostma** [comment]
yes, I think it is

**Comment by MarinPostma** [comment]
closed by #1521
