### ISSUE TITLE
frontend package.. create repository..

### ISSUE THREAD

**Issue by 7flash** [chiselstrike/chiselstrike#1508]
![image](https://user-images.githubusercontent.com/4569866/176870596-5a7527d5-4c61-468c-bd2e-d85119ac7c46.png)

Couldn't find it on github.. but found here..

https://socket.dev/npm/package/@chiselstrike/frontend/files/0.9.1/index.mjs#T394-401

**Comment by penberg** [comment]
The frontend package was removed in 0.10.0 release as we migrated to NextAuth.
