### ISSUE TITLE
req.pathParams doesn't include `?` parameters

### ISSUE THREAD

**Issue by 7flash** [chiselstrike/chiselstrike#1512]
![image](https://user-images.githubusercontent.com/4569866/176983113-66fa274a-3fdd-4358-a9e6-50ba0bd30406.png)

![image](https://user-images.githubusercontent.com/4569866/176983059-cf118a2f-7334-4226-9045-34ba976e757a.png)

Expected to see "today" in path params.. but it's an empty string..

![image](https://user-images.githubusercontent.com/4569866/176983107-f83c4366-7de3-41b0-b4f4-186c45891bf3.png)

**Comment by 7flash** [comment]
Temporary alternative works.. extracting params from url..

```
        const payload = new URLSearchParams(
            req.url.substring(req.url.indexOf('?'))
        );

        const date = payload.get('date');
```

**Comment by ricardodalarme** [comment]
This isn't a `path param`, it's actually a `search param` and you can get it in a simpler way:

```
const url = new URL(req.url);
const teamName = url.searchParams.get('date')
```
