### ISSUE TITLE
bad message when importing non-existent files - deno mode

### ISSUE THREAD

**Issue by glommer** [chiselstrike/chiselstrike#1533]
When playing with a deno-mode project, I had a typo and referred to a non-existent file.

The error message doesn't include the file name, so it is very hard to debug:

```
$ chisel apply
Error: parsing endpoints

Caused by:
    No such file or directory (os error 2)
```

@espindola I can try to take a look later, but I am hoping you know the exact place of this ?

**Comment by honzasp** [comment]
This might be fixed by #1556, when I try to import a non-existent file, I get this error:

```
could not compile endpoints (using deno-style modules)

Caused by:
    0: could not compile TypeScript
    1: failed to load module file:///home/jan/prog/chiselstrike/test_deno/endpoints/does/not/exist
    2: No such file or directory (os error 2)
```
