### ISSUE TITLE
Type annotation in model is ignored when there is a default value

### ISSUE THREAD

**Issue by honzasp** [chiselstrike/chiselstrike#1598]
In this model, the field `isCool` is inferred to have type `number` (from the default value), even though the explicit type annotation says `boolean`:

```ts
import { ChiselEntity } from '@chiselstrike/api';

export class Human extends ChiselEntity {
    name: string;
    isCool: boolean = 1;
}
```

Expected behavior is either that `isCool` is a `boolean` or an error. Note that typechecking fails in this case.

**Comment by dekimir** [comment]
> Note that typechecking fails in this case.

Does that mean that `chisel apply` fails?  If so, then the inferred type is immaterial, as the model definition is rejected.  If not, then which typechecking is this, and why does it matter?

**Comment by honzasp** [comment]
`chisel apply --type-check` rejects this code, but `chisel apply` accepts it, because typechecking is disabled by default. It matters because it means that users are less likely to hit this bug in practice, because their IDE will hopefully type-check their code and display a warning.
