### ISSUE TITLE
vscode devcontainer - Cannot assign requested address

### ISSUE THREAD

**Issue by 7flash** [chiselstrike/chiselstrike#1716]
![image](https://user-images.githubusercontent.com/4569866/187058697-44adb19c-e197-4f05-81b7-3c4d16035237.png)

**Comment by penberg** [comment]
Hey @7flash, this seems like a duplicate of https://github.com/chiselstrike/chiselstrike/issues/1216, no? It's a Docker bug AFAICT, which we don't really understand how to work around.

**Comment by 7flash** [comment]
What is the proper way to specify custom port now?

https://github.com/chiselstrike/chiselstrike/commit/f699eabf2e05d269e07bf08e3b197c578eae3321#diff-37970e7d817d4316a093bb967d74ff7e26d9c6c01d93f5a79d3d195ba9f6155bL83

**Comment by penberg** [comment]
@7flash You can pass all `chiseld` arguments via `chisel start` by adding a `--` and then passing the parameters.

For example, to specify the API listen address, type:

```
chisel start -- --api-listen-addr 127.0.0.1:8081
```

**Comment by 7flash** [comment]
Thx!

It works in dev container:

```
./target/debug/chiseld --api-listen-addr 127.0.0.1:8081
[2022-08-28T07:54:16Z] INFO - ChiselStrike is ready 🚀 - URL: http://127.0.0.1:8081
```

Also following works to launch second instance:

```
    "scripts": {
        "dev": "chisel dev",
        "start": "chisel start -- --internal-routes-listen-addr 127.0.0.1:9091"
    }
    
    pm2 start npm --name "db-galaxy-first" -- start
```

**Comment by 7flash** [comment]
Though regarding second instance.. it's api listens on the same port as first one.. wouldn't that conflict?

**Comment by 7flash** [comment]
Also, when I run multiple instances, does CLI detect which one to interact with by its context?

```
npx chisel apply --allow-type-deletion
```

**Comment by 7flash** [comment]
It works properly:

```
    "scripts": {
        "dev": "chisel dev",
        "start": "chisel start -- --internal-routes-listen-addr 127.0.0.1:28081 --api-listen-addr 127.0.0.1:28082 --rpc-listen-addr 127.0.0.1:28083",
        "apply": "chisel --rpc-addr http://127.0.0.1:28083 apply --allow-type-deletion"
    },

```
