### ISSUE TITLE
chiselc is broken

### ISSUE THREAD

**Issue by glommer** [chiselstrike/chiselstrike#1840]
Everytime I run tests now on main, I see a message saying:
```
Warning: no ChiselStrike compiler (`chiselc`) found. Some of your queries might be slow.
```

Digging, chiselc is in the path, and we call the probe successfully. However, the probe is `chiselc --version`, and that fails if executed manually:

```
/Users/glaubercosta/chiselstrike/target/debug/chiselc --version
error: Found argument '--version' which wasn't expected, or isn't valid in this context

  If you tried to supply '--version' as a value rather than a flag, use '-- --version'

Usage: chiselc [OPTIONS] [INPUT]

For more information try '--help'
```

So something changed recently, that made chiselc no longer accept that option.

@BearLemma please fix this and let's add a test making sure that chiselc is always working when it is expected to.

**Comment by honzasp** [comment]
Perhaps this is related to the latest clap-related changes?
https://github.com/chiselstrike/chiselstrike/pull/1822

**Comment by psarna** [comment]
@honzasp guys, if you suspect it in the slightest bit, feel free to revert #1822, I did it as a newbie issue only and it's in no way critical
