### ISSUE TITLE
Unable to use `var img = new Image();` in endpoint

### ISSUE THREAD

**Issue by BearLemma** [chiselstrike/chiselstrike#198]
I would like to use `Image` class in my chisel endpoint to parse an image and determine it's size. That turned out to be impossible as the endpoint seems to crash (return 500) immediately after I create the variable. Minimal endpoint to reproduce:

```
export default async function chisel(req) {
    var img = new Image();
}
```
I suspect that Image internally uses window or something which Deno doesn't provide. Chiseld also doesn't provide any useful debugging log or message.

**Comment by penberg** [comment]
@BearLemma I am closing this issue as stale.
