### ISSUE TITLE
Doesn't run from example

### ISSUE THREAD

**Issue by nikitavoloboev** [chiselstrike/chiselstrike#1980]
I followed quick start example with just a change to the name and model. My repo here:

https://github.com/nikitavoloboev/test/tree/main/chiselstrike

When I run it with `pnpm run dev` or `npm run dev`. And then run curl command in readme. I get this:

```
curl -X POST -d '{"title": "chiselstrike", "url": "https://github.com/chiselstrike/chiselstrike"}' localhost:8080/dev/links
There is no route for "/links"⏎ 
```

**Comment by nikitavoloboev** [comment]
It could be that I mistook where I should create `endpoints` folder. In readme it doesn't really say where to make it so I thought it would be at root.

**Comment by penberg** [comment]
@nikitavoloboev Please use a `routes` directory instead of `endpoints` (which is deprecated). Can you point me to the part in documentation that still mentions `endpoints` so we can fix it?

/cc @CodingDoug

**Comment by nikitavoloboev** [comment]
https://github.com/chiselstrike/chiselstrike#quick-start

> Add an endpoint by writing the following TypeScript code to endpoints/comments.ts

**Comment by nikitavoloboev** [comment]
Ok this works, will close this. ❤️
