### ISSUE TITLE
Relationships: create a blogpost referencing existing author?

### ISSUE THREAD

**Issue by 7flash** [chiselstrike/chiselstrike#1986]
Currently in docs example it would create a new author every time creating a blog post, but would it be possible to pass ID of existing author entity and avoid duplication?

**Comment by 7flash** [comment]
https://docs.chiselstrike.com/reference/entity-crud-api/relationships#add

**Comment by CodingDoug** [comment]
For that, you would want to use an indirect relationship using an `Id<>` type field.
https://docs.chiselstrike.com/reference/data-modeling/relationships#indirect-relationships
