### ISSUE TITLE
Maybe use Web Workers for endpoints

### ISSUE THREAD

**Issue by espindola** [chiselstrike/chiselstrike#433]
From today's meeting, using Web Workers might be a way to have more sync APIs while still using V8 and not blocking an entire system thread.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by penberg** [comment]
Fixed by 872f329addcd51a2da4c60ab360ae952a82cd10e, right, @espindola?
