### ISSUE TITLE
make it easier to return values

### ISSUE THREAD

**Issue by glommer** [chiselstrike/chiselstrike#495]
Based on Profusion's feedback:

Since we control the runtime, one extra level of usability improvement is that we could allow the user to write directly:

```
return Person.filter(...).select('name').take(2)
```

that would automatically convert to json, generate a response, etc.

They suggested even some pseudocode for that:

```
const response = await endpoint(req); // call your function above, the one with Person.filter...
if (response instanceof Response) return response;
if (response instanceof SomethingElseThatIsABaseClassForPerson) {
   return new Response(JSON.stringify(response.toJson()), // or toArray?
               { status: 200, headers: [["content-type", "application/json"]] });
}
...
```

And as a follow up, even the fact that we can use streaming here to write the objects to the socket as they get ready.

Maybe we can do this in Rust, especially the streaming part, so I am so far just opening this issue and won't really work on it.
It is a really nice usability improvement, so I think we should do it.

**Comment by penberg** [comment]
@glommer this is fixed as of 14908d1e3a0c6d1db4086cd23c82c925e43058ea, no?
